name: "harsha_portfolio"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  
    image: saisriharsha2005/harsha_portfolio_dev:latest
    volumes:
      - .:/note-nexus/frontend/ 
      - /note-nexus/frontend/node_modules  
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true
    tty: true
