# Stage 1: Base Image for Development
FROM node:23-alpine AS base

# Set the working directory
WORKDIR /harsha_portfolio/

# Copy only package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --no-cache

# Copy only necessary source files
COPY . .
# Expose the React development server port
EXPOSE 3000

# Command to run the development server with hot reloading
CMD ["npm", "run", "dev"]
