name: "harsha_portfolio"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Map React's default dev server port
    image: saisriharsha2005/harsha_portfolio_dev:latest
    volumes:
      - .:/note-nexus/frontend/  # Mount project directory for hot reloading
      - /note-nexus/frontend/node_modules  # Exclude node_modules to avoid conflicts
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file change detection in Docker
    stdin_open: true
    tty: true
