services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"  
    image: saisriharsha2005/harsha_portfolio_dev:latest
    volumes:
      - .:/harsha_portfolio
      - /harsha_portfolio/node_modules
    container_name: frontend
    networks:
      - network
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000

networks:
  network:
    driver: bridge