name: "harsha_portfolio"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    image: saisriharsha2005/harsha_portfolio_prod:latest
    ports:
      - "80:80"  # Serve the app on HTTP port 80
    restart: always
