import solomons from "../../images/solomons.png";
import solomons_experience_letter from "../../images/solomons_experience_letter.jpg";

export const experiences = [
  {
    id: 0,
    img: "https://mms.businesswire.com/media/20220421005466/en/1427984/5/TCSLogo2.jpg",
    role: "DevOps Engineer",
    company: "Tata Consultancy Services",
    date: "October 2024 - Present",
    desc: "As a DevOps Engineer at TCS, I maintain pipelines and perform installation, upgrade (II UG), rollback, backup, and restore tasks for Ericsson applications. I work on CI/CD pipelines and containerized deployments using Jenkins, Docker, and Kubernetes. I also collaborate with Ericsson’s DevOps team to streamline deployments and manage infrastructure across their microservices.",
    skills: [
      "Docker",
      "Kubernetees",
      "Devops",
      "Jenkins",
      "CI/CD",
      "Git",
      "Groovy",
      "Ansible",
      "Python",
      "Bash Scripting",
      "Linux",
    
    ],
  },
  {
    id: 1,
    img: "https://mms.businesswire.com/media/20220421005466/en/1427984/5/TCSLogo2.jpg",
    role: "ILP Trainee",
    company: "Tata Consultancy Services",
    date: "August 2024 - September 2024",
    desc: "During my ILP training, I contributed to the development of SmartBill, an electricity billing portal built with Java, JSP, Servlets, and JDBC. I implemented admin features for managing consumer details and billing, along with consumer-side functionalities such as multi-consumer registration, bill viewing, payment tracking, and complaint management.  I was recognized as one of the top six performers based on my performance in exams and case studies throughout the training.",
    skills: [
      "HTML",
      "CSS",
      "Java",
      "Javscript",
      "Java Server Pages (JSP)",
      "Servlets",
      "Derby",
    ],
  },
  {
    id: 2,
    img: solomons,
    role: "Full Stack NLP Engineer Intern",
    company: "Solomons International",
    date: "September 2023 - February 2024",
    desc: "During my internship at Solomons International Technologies, I worked on multiple projects that strengthened my skills in NLP and full-stack development. I developed a resume classification system to categorize profiles into roles like software developer using machine learning techniques. I also built a Named Entity Recognition (NER) system to extract entities such as names, organizations, and locations from text. Additionally, I worked on topic modeling to generate meaningful insights from textual data and implemented a document matching system to compare job descriptions with resumes and assign relevance scores. These experiences enhanced my practical understanding of NLP and its real-world applications, while improving my problem-solving and development skills.",
    skills: [
      "HTML",
      "CSS",
      "JavaSrcipt",
      "React.js",
      "TailwindCSS",
      "MongoDB",
      "SQL",
      "OpenAI API",
      "Node.js",
      "Material UI",
      "Python",
      "Flask",
      "Machine Learning",
      "NLP",
    ],
    doc: solomons_experience_letter,
  },
];
