import solomons from "../../images/solomons.webp";
import internshala from "../../images/internshala.jpg";

export const experiences = [
  {
    id: 0,
    img: "https://mms.businesswire.com/media/20220421005466/en/1427984/5/TCSLogo2.jpg",
    role: "DevOps Engineer",
    company: "Tata Consultancy Services",
    date: "August 2024 - Present",
    desc: "During my ILP training, I was recognized as one of the top six performers based on my performance in exams and case studies conducted throughout the program",
    skills: [
      "HTML",
      "CSS",
      "Java",
      "Javscript",
      "Java Server Pages (JSP)",
      "Java Full Stack Web Development",
      "Servlets",
      "Docker",
      "Kubernetees",
      "Devops"
    ],
  },
  {
    id: 1,
    img: solomons,
    role: "Full Stack NLP Engineer Intern",
    company: "Solomons International",
    date: "September 2023 - February 2024",
    desc: "During my internship at Solomons International Technologies, I had the opportunity to work on a variety of projects that significantly enhanced my skills in natural language processing (NLP) and full-stack development. One of the projects involved developing a system for document classification, specifically for resumes, where I implemented algorithms to accurately categorize resumes into different classifications such as software developer or other custom categories provided by the user. Additionally, I worked on a named entity recognition (NER) project, where I developed algorithms to extract specific entities from text, such as names, organizations, and locations. Another project I undertook was topic modeling, where I created a system to generate relevant topics from text using machine learning algorithms. Lastly, I worked on a document matching project, where I developed an algorithm to match job orders with resumes and generate a score based on the relevance of the match. These projects not only improved my technical skills but also provided me with valuable insights into the practical applications of NLP. I am grateful for the experience and look forward to applying these skills in future projects.",
    skills: [
      "HTML",
      "CSS",
      "JavaSrcipt",
      "React.js",
      "TailwindCSS",
      "MongoDB",
      "SQL",
      "OpenAI API",
      "Node.js",
      "Material UI",
      "Python",
      "Flask",
      "Machine Learning",
      "Natural Language Processing",
    ],
    doc: "https://firebasestorage.googleapis.com/v0/b/harshaportfolio-2005.appspot.com/o/Rankela%20Sai%20Sri%20Harsha%20Internship%20Certificate-signed_page-0001.jpg?alt=media&token=1932c9d3-273c-45eb-a7ba-bee5dfa8da45",
  },
  {
    id: 2,
    img: internshala,
    role: "Web Developer Intern",
    company: "Internshala",
    date: "July 2023 - September 2023",
    desc: "During my internship with Internshala Remote, I played a key role in developing the responsive web interface for PG Life. Using HTML, CSS, and JavaScript, I crafted a user-friendly experience that garnered positive feedback for its usability. Additionally, I focused on enhancing user engagement by implementing a contemporary design and strategically utilizing Bootstrap. This approach led to a significant increase in the average session duration, reflecting the success of the project. Furthermore, I took charge of revamping the PHP and MySQL database integration in PG Life, achieving an impressive average response time of less than 100ms. To ensure efficient version control and streamlined query execution, I implemented Git for Version Control and SQL. These efforts collectively contributed to the optimization of PG Life's performance and user experience.",
    skills: ["HTML", "CSS", "BootStrap", "JavaScript", "MySQL", "PHP"],
    doc: "https://firebasestorage.googleapis.com/v0/b/harshaportfolio-2005.appspot.com/o/Web%20Development%20Training%20-%20Certificate%20of%20Completion_page-0001.jpg?alt=media&token=5b8c8501-e605-451f-83d9-dc9695e4c54f",
  },
];
