import solomons from "../../images/solomons.png";

export const experiences = [
  {
    id: 0,
    img: "https://mms.businesswire.com/media/20220421005466/en/1427984/5/TCSLogo2.jpg",
    role: "DevOps Engineer",
    company: "Tata Consultancy Services",
    date: "October 2024 - Present",
    desc: "As a DevOps Engineer at TCS, I maintain pipelines and perform installation, upgrade (II UG), rollback, backup, and restore tasks for Ericsson applications. I work on CI/CD pipelines and containerized deployments using Jenkins, Docker, and Kubernetes. I also collaborate with Ericsson’s DevOps team to streamline deployments and manage infrastructure across their microservices.",
    skills: [
      "Docker",
      "Kubernetees",
      "Devops",
      "Jenkins",
      "CI/CD",
      "Git",
      "Groovy",
      "Ansible",
      "Python",
      "Bash Scripting",
      "Linux",
    
    ],
  },
  {
    id: 1,
    img: "https://mms.businesswire.com/media/20220421005466/en/1427984/5/TCSLogo2.jpg",
    role: "ILP Trainee",
    company: "Tata Consultancy Services",
    date: "August 2024 - September 2024",
    desc: "During my ILP training, I contributed to the development of SmartBill, an electricity billing portal built with Java, JSP, Servlets, and JDBC. I implemented admin features for managing consumer details and billing, along with consumer-side functionalities such as multi-consumer registration, bill viewing, payment tracking, and complaint management.  I was recognized as one of the top six performers based on my performance in exams and case studies throughout the training.",
    skills: [
      "HTML",
      "CSS",
      "Java",
      "Javscript",
      "Java Server Pages (JSP)",
      "Servlets",
      "Derby",
    ],
  },
  {
    id: 2,
    img: solomons,
    role: "Full Stack NLP Engineer Intern",
    company: "Solomons International",
    date: "September 2023 - February 2024",
    desc: "During my internship at Solomons International Technologies, I had the opportunity to work on a variety of projects that significantly enhanced my skills in NLP (NLP) and full-stack development. One of the projects involved developing a system for document classification, specifically for resumes, where I implemented algorithms to accurately categorize resumes into different classifications such as software developer or other custom categories provided by the user. Additionally, I worked on a named entity recognition (NER) project, where I developed algorithms to extract specific entities from text, such as names, organizations, and locations. Another project I undertook was topic modeling, where I created a system to generate relevant topics from text using machine learning algorithms. Lastly, I worked on a document matching project, where I developed an algorithm to match job orders with resumes and generate a score based on the relevance of the match. These projects not only improved my technical skills but also provided me with valuable insights into the practical applications of NLP. I am grateful for the experience and look forward to applying these skills in future projects.",
    skills: [
      "HTML",
      "CSS",
      "JavaSrcipt",
      "React.js",
      "TailwindCSS",
      "MongoDB",
      "SQL",
      "OpenAI API",
      "Node.js",
      "Material UI",
      "Python",
      "Flask",
      "Machine Learning",
      "NLP",
    ],
    doc: "https://firebasestorage.googleapis.com/v0/b/harshaportfolio-2005.appspot.com/o/Rankela%20Sai%20Sri%20Harsha%20Internship%20Certificate-signed_page-0001.jpg?alt=media&token=1932c9d3-273c-45eb-a7ba-bee5dfa8da45",
  },
];
